module.exports = [
    {
        vegetarian: true,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 37,
        gaps: "no",
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 11,
        healthScore: 3,
        creditsText:
            "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 153.59,
        extendedIngredients: [
            {
                id: 1089003,
                aisle: "Produce",
                image: "grannysmith-apple.png",
                consistency: "SOLID",
                name: "granny smith apples",
                nameClean: "granny smith apple",
                original:
                    "4 cups Granny Smith apples, chopped into ½ inch chunks",
                originalName: "Granny Smith apples, chopped into ½ inch chunks",
                amount: 4.0,
                unit: "cups",
                meta: ["chopped"],
                measures: {
                    us: {
                        amount: 4.0,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 946.352,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 9078,
                aisle: "Produce",
                image: "cranberries.jpg",
                consistency: "SOLID",
                name: "cranberries",
                nameClean: "cranberries",
                original: "2 cups fresh cranberries",
                originalName: "fresh cranberries",
                amount: 2.0,
                unit: "cups",
                meta: ["fresh"],
                measures: {
                    us: {
                        amount: 2.0,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 473.176,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 19335,
                aisle: "Baking",
                image: "sugar-in-bowl.png",
                consistency: "SOLID",
                name: "sugar",
                nameClean: "sugar",
                original: "1 cup sugar",
                originalName: "sugar",
                amount: 1.0,
                unit: "cup",
                meta: [],
                measures: {
                    us: {
                        amount: 1.0,
                        unitShort: "cup",
                        unitLong: "cup",
                    },
                    metric: {
                        amount: 236.588,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 1145,
                aisle: "Milk, Eggs, Other Dairy",
                image: "butter-sliced.jpg",
                consistency: "SOLID",
                name: "butter",
                nameClean: "unsalted butter",
                original: "1/2 stick (4 Tbs) unsalted butter, cut into cubes",
                originalName: "1/2 stick unsalted butter, cut into cubes",
                amount: 4.0,
                unit: "Tbs",
                meta: ["unsalted", "cut into cubes"],
                measures: {
                    us: {
                        amount: 4.0,
                        unitShort: "Tbs",
                        unitLong: "Tbs",
                    },
                    metric: {
                        amount: 4.0,
                        unitShort: "Tbs",
                        unitLong: "Tbs",
                    },
                },
            },
            {
                id: 8120,
                aisle: "Cereal",
                image: "rolled-oats.jpg",
                consistency: "SOLID",
                name: "regular oats",
                nameClean: "rolled oats",
                original: "1 1/2 cups regular oats (not quick-cooking)",
                originalName: "regular oats (not quick-cooking)",
                amount: 1.5,
                unit: "cups",
                meta: ["(not quick-cooking)"],
                measures: {
                    us: {
                        amount: 1.5,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 354.882,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 19334,
                aisle: "Baking",
                image: "light-brown-sugar.jpg",
                consistency: "SOLID",
                name: "brown sugar",
                nameClean: "golden brown sugar",
                original: "1/2 cup light brown sugar",
                originalName: "light brown sugar",
                amount: 0.5,
                unit: "cup",
                meta: ["light"],
                measures: {
                    us: {
                        amount: 0.5,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 118.294,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 20081,
                aisle: "Baking",
                image: "flour.png",
                consistency: "SOLID",
                name: "flour",
                nameClean: "wheat flour",
                original: "1/4 cup all-purpose flour",
                originalName: "all-purpose flour",
                amount: 0.25,
                unit: "cup",
                meta: ["all-purpose"],
                measures: {
                    us: {
                        amount: 0.25,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 59.147,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 1145,
                aisle: "Milk, Eggs, Other Dairy",
                image: "butter-sliced.jpg",
                consistency: "SOLID",
                name: "butter",
                nameClean: "unsalted butter",
                original: "1 stick unsalted butter, melted",
                originalName: "unsalted butter, melted",
                amount: 1.0,
                unit: "stick",
                meta: ["unsalted", "melted"],
                measures: {
                    us: {
                        amount: 1.0,
                        unitShort: "stick",
                        unitLong: "stick",
                    },
                    metric: {
                        amount: 1.0,
                        unitShort: "stick",
                        unitLong: "stick",
                    },
                },
            },
        ],
        id: 640352,
        title: "Cranberry Apple Crisp",
        readyInMinutes: 45,
        servings: 4,
        sourceUrl:
            "https://www.foodista.com/recipe/TJXDHDFD/cranberry-apple-crisp",
        image: "https://spoonacular.com/recipeImages/640352-556x370.jpg",
        imageType: "jpg",
        summary:
            'Need a <b>lacto ovo vegetarian dessert</b>? Cranberry Apple Crisp could be an excellent recipe to try. This recipe serves 4. One serving contains <b>833 calories</b>, <b>6g of protein</b>, and <b>37g of fat</b>. For <b>$1.54 per serving</b>, this recipe <b>covers 13%</b> of your daily requirements of vitamins and minerals. 11 person were glad they tried this recipe. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. If you have butter, regular oats, sugar, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. Overall, this recipe earns a <b>not so awesome spoonacular score of 36%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/apple-cranberry-crisp-55221">Apple Cranberry Crisp</a>, <a href="https://spoonacular.com/recipes/the-best-cranberry-apple-crisp-1053025">The Best Cranberry Apple Crisp</a>, and <a href="https://spoonacular.com/recipes/apple-cranberry-crisp-128913">Apple Cranberry Crisp</a>.',
        cuisines: [],
        dishTypes: ["dessert"],
        diets: ["lacto ovo vegetarian"],
        occasions: [],
        winePairing: {
            pairedWines: ["cream sherry", "port", "moscato dasti"],
            pairingText:
                "Crisp works really well with Cream Sherry, Port, and Moscato d'Asti. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. You could try NV Solera Cream Sherry. Reviewers quite like it with a 4.5 out of 5 star rating and a price of about 17 dollars per bottle.",
            productMatches: [
                {
                    id: 428475,
                    title: "NV Solera Cream Sherry",
                    description:
                        "The Solera Cream Sherry has a brilliant amber and deep copper hue. With butterscotch and pecan aromas, the sweet salted nut and brown spice aromas carry a complex caramel accent. A sweet entry leads to a rounded, lush, moderately full-bodied palate with a lengthy, flavorful finish.",
                    price: "$16.99",
                    imageUrl:
                        "https://spoonacular.com/productImages/428475-312x231.jpg",
                    averageRating: 0.9,
                    ratingCount: 4.0,
                    score: 0.823076923076923,
                    link: "https://www.amazon.com/NV-Solera-Cream-Sherry-750/dp/B00HSME8OW?tag=spoonacular-20",
                },
            ],
        },
        instructions:
            "Preheat the oven to 350 degrees and grease or butter a 913 glass baking dish.\nIn a large bowl, toss together the chopped apples, cranberries and sugar. Let stand for a few minutes then pour into the baking dish.\nDot the mixture with the 1/2 stick of cubed butter.\nIn a medium bowl, combine the oats, brown sugar and flour.  Sprinkle evenly over the cranberries and apples in the baking dish.  Gently pour the melted butter over the top.\nCover with aluminum foil and bake for 35 minutes.  Remove the foil and bake for an additional 15 minutes, or until the oat topping is nicely browned.\nServe warm as a side or for dessert with a scoop of vanilla ice cream.",
        analyzedInstructions: [
            {
                name: "",
                steps: [
                    {
                        number: 1,
                        step: "Preheat the oven to 350 degrees and grease or butter a 913 glass baking dish.",
                        ingredients: [
                            {
                                id: 1001,
                                name: "butter",
                                localizedName: "butter",
                                image: "butter-sliced.jpg",
                            },
                        ],
                        equipment: [
                            {
                                id: 406921,
                                name: "glass baking pan",
                                localizedName: "glass baking pan",
                                image: "glass-baking-tray.jpg",
                            },
                            {
                                id: 404784,
                                name: "oven",
                                localizedName: "oven",
                                image: "oven.jpg",
                            },
                        ],
                    },
                    {
                        number: 2,
                        step: "In a large bowl, toss together the chopped apples, cranberries and sugar.",
                        ingredients: [
                            {
                                id: 9078,
                                name: "cranberries",
                                localizedName: "cranberries",
                                image: "cranberries.jpg",
                            },
                            {
                                id: 9003,
                                name: "apple",
                                localizedName: "apple",
                                image: "apple.jpg",
                            },
                            {
                                id: 19335,
                                name: "sugar",
                                localizedName: "sugar",
                                image: "sugar-in-bowl.png",
                            },
                        ],
                        equipment: [
                            {
                                id: 404783,
                                name: "bowl",
                                localizedName: "bowl",
                                image: "bowl.jpg",
                            },
                        ],
                    },
                    {
                        number: 3,
                        step: "Let stand for a few minutes then pour into the baking dish.",
                        ingredients: [],
                        equipment: [
                            {
                                id: 404646,
                                name: "baking pan",
                                localizedName: "baking pan",
                                image: "roasting-pan.jpg",
                            },
                        ],
                    },
                    {
                        number: 4,
                        step: "Dot the mixture with the 1/2 stick of cubed butter.",
                        ingredients: [
                            {
                                id: 1001,
                                name: "butter",
                                localizedName: "butter",
                                image: "butter-sliced.jpg",
                            },
                        ],
                        equipment: [],
                    },
                    {
                        number: 5,
                        step: "In a medium bowl, combine the oats, brown sugar and flour.",
                        ingredients: [
                            {
                                id: 19334,
                                name: "brown sugar",
                                localizedName: "brown sugar",
                                image: "dark-brown-sugar.png",
                            },
                            {
                                id: 20081,
                                name: "all purpose flour",
                                localizedName: "all purpose flour",
                                image: "flour.png",
                            },
                            {
                                id: 8120,
                                name: "oats",
                                localizedName: "oats",
                                image: "rolled-oats.jpg",
                            },
                        ],
                        equipment: [
                            {
                                id: 404783,
                                name: "bowl",
                                localizedName: "bowl",
                                image: "bowl.jpg",
                            },
                        ],
                    },
                    {
                        number: 6,
                        step: "Sprinkle evenly over the cranberries and apples in the baking dish.  Gently pour the melted butter over the top.",
                        ingredients: [
                            {
                                id: 9078,
                                name: "cranberries",
                                localizedName: "cranberries",
                                image: "cranberries.jpg",
                            },
                            {
                                id: 9003,
                                name: "apple",
                                localizedName: "apple",
                                image: "apple.jpg",
                            },
                            {
                                id: 1001,
                                name: "butter",
                                localizedName: "butter",
                                image: "butter-sliced.jpg",
                            },
                        ],
                        equipment: [
                            {
                                id: 404646,
                                name: "baking pan",
                                localizedName: "baking pan",
                                image: "roasting-pan.jpg",
                            },
                        ],
                    },
                    {
                        number: 7,
                        step: "Cover with aluminum foil and bake for 35 minutes.",
                        ingredients: [],
                        equipment: [
                            {
                                id: 404765,
                                name: "aluminum foil",
                                localizedName: "aluminum foil",
                                image: "aluminum-foil.png",
                            },
                            {
                                id: 404784,
                                name: "oven",
                                localizedName: "oven",
                                image: "oven.jpg",
                            },
                        ],
                        length: {
                            number: 35,
                            unit: "minutes",
                        },
                    },
                    {
                        number: 8,
                        step: "Remove the foil and bake for an additional 15 minutes, or until the oat topping is nicely browned.",
                        ingredients: [],
                        equipment: [
                            {
                                id: 404784,
                                name: "oven",
                                localizedName: "oven",
                                image: "oven.jpg",
                            },
                            {
                                id: 404765,
                                name: "aluminum foil",
                                localizedName: "aluminum foil",
                                image: "aluminum-foil.png",
                            },
                        ],
                        length: {
                            number: 15,
                            unit: "minutes",
                        },
                    },
                    {
                        number: 9,
                        step: "Serve warm as a side or for dessert with a scoop of vanilla ice cream.",
                        ingredients: [
                            {
                                id: 19095,
                                name: "vanilla ice cream",
                                localizedName: "vanilla ice cream",
                                image: "vanilla-ice-cream.png",
                            },
                        ],
                        equipment: [],
                    },
                ],
            },
        ],
        originalId: null,
        spoonacularSourceUrl:
            "https://spoonacular.com/cranberry-apple-crisp-640352",
    },
    {
        vegetarian: true,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 92,
        gaps: "no",
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 1,
        healthScore: 16,
        creditsText:
            "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 386.98,
        extendedIngredients: [
            {
                id: 9003,
                aisle: "Produce",
                image: "apple.jpg",
                consistency: "SOLID",
                name: "apples",
                nameClean: "apple",
                original: "3 apples – sliced",
                originalName: "apples – sliced",
                amount: 3.0,
                unit: "",
                meta: ["sliced"],
                measures: {
                    us: {
                        amount: 3.0,
                        unitShort: "",
                        unitLong: "",
                    },
                    metric: {
                        amount: 3.0,
                        unitShort: "",
                        unitLong: "",
                    },
                },
            },
            {
                id: 19334,
                aisle: "Baking",
                image: "light-brown-sugar.jpg",
                consistency: "SOLID",
                name: "brown sugar",
                nameClean: "golden brown sugar",
                original: "1/2 cup of brown sugar",
                originalName: "brown sugar",
                amount: 0.5,
                unit: "cup",
                meta: [],
                measures: {
                    us: {
                        amount: 0.5,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 118.294,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 1001,
                aisle: "Milk, Eggs, Other Dairy",
                image: "butter-sliced.jpg",
                consistency: "SOLID",
                name: "butter",
                nameClean: "butter",
                original: "3/4 stick of butter",
                originalName: "butter",
                amount: 0.75,
                unit: "stick",
                meta: [],
                measures: {
                    us: {
                        amount: 0.75,
                        unitShort: "stick",
                        unitLong: "sticks",
                    },
                    metric: {
                        amount: 0.75,
                        unitShort: "stick",
                        unitLong: "sticks",
                    },
                },
            },
            {
                id: 2011,
                aisle: "Spices and Seasonings",
                image: "cloves.jpg",
                consistency: "SOLID",
                name: "ground cloves",
                nameClean: "ground clove",
                original: "Dash of ground cloves",
                originalName: "ground cloves",
                amount: 1.0,
                unit: "Dash",
                meta: [],
                measures: {
                    us: {
                        amount: 1.0,
                        unitShort: "Dash",
                        unitLong: "Dash",
                    },
                    metric: {
                        amount: 1.0,
                        unitShort: "Dash",
                        unitLong: "Dash",
                    },
                },
            },
            {
                id: 20081,
                aisle: "Baking",
                image: "flour.png",
                consistency: "SOLID",
                name: "flour",
                nameClean: "wheat flour",
                original: "1 cup of flour",
                originalName: "flour",
                amount: 1.0,
                unit: "cup",
                meta: [],
                measures: {
                    us: {
                        amount: 1.0,
                        unitShort: "cup",
                        unitLong: "cup",
                    },
                    metric: {
                        amount: 236.588,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
            {
                id: 9156,
                aisle: "Produce",
                image: "zest-lemon.jpg",
                consistency: "SOLID",
                name: "lemon zest",
                nameClean: "lemon peel",
                original: "1 Zest of lemon",
                originalName: "Zest of lemon",
                amount: 1.0,
                unit: "",
                meta: [],
                measures: {
                    us: {
                        amount: 1.0,
                        unitShort: "",
                        unitLong: "",
                    },
                    metric: {
                        amount: 1.0,
                        unitShort: "",
                        unitLong: "",
                    },
                },
            },
            {
                id: 19335,
                aisle: "Baking",
                image: "sugar-in-bowl.png",
                consistency: "SOLID",
                name: "sugar",
                nameClean: "sugar",
                original: "1/2 cup of sugar",
                originalName: "sugar",
                amount: 0.5,
                unit: "cup",
                meta: [],
                measures: {
                    us: {
                        amount: 0.5,
                        unitShort: "cups",
                        unitLong: "cups",
                    },
                    metric: {
                        amount: 118.294,
                        unitShort: "ml",
                        unitLong: "milliliters",
                    },
                },
            },
        ],
        id: 641803,
        title: "Easy & Delish! ~ Apple Crumble",
        readyInMinutes: 45,
        servings: 1,
        sourceUrl:
            "http://www.foodista.com/recipe/3BCP244Z/easy-delish-apple-crumble",
        image: "https://spoonacular.com/recipeImages/641803-556x370.jpg",
        imageType: "jpg",
        summary:
            'Easy & Delish! ~ Apple Crumble is a dessert that serves 1. One portion of this dish contains about <b>15g of protein</b>, <b>71g of fat</b>, and a total of <b>2155 calories</b>. For <b>$3.87 per serving</b>, this recipe <b>covers 31%</b> of your daily requirements of vitamins and minerals. It is a good option if you\'re following a <b>lacto ovo vegetarian</b> diet. 1 person has made this recipe and would make it again. Head to the store and pick up sugar, brown sugar, butter, and a few other things to make it today. It is brought to you by Foodista. From preparation to the plate, this recipe takes around <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 75%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/easy-apple-pear-crumble-835515">Easy Apple Pear Crumble</a>, <a href="https://spoonacular.com/recipes/easy-apple-crumble-pie-48372">Easy Apple Crumble Pie</a>, and <a href="https://spoonacular.com/recipes/easy-apple-crumble-bars-1137632">Easy Apple Crumble Bars</a>.',
        cuisines: [],
        dishTypes: ["dessert"],
        diets: ["lacto ovo vegetarian"],
        occasions: [],
        winePairing: {
            pairedWines: ["cream sherry", "port", "moscato dasti"],
            pairingText:
                "Crumble works really well with Cream Sherry, Port, and Moscato d'Asti. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. You could try NV Solera Cream Sherry. Reviewers quite like it with a 4.5 out of 5 star rating and a price of about 17 dollars per bottle.",
            productMatches: [
                {
                    id: 428475,
                    title: "NV Solera Cream Sherry",
                    description:
                        "The Solera Cream Sherry has a brilliant amber and deep copper hue. With butterscotch and pecan aromas, the sweet salted nut and brown spice aromas carry a complex caramel accent. A sweet entry leads to a rounded, lush, moderately full-bodied palate with a lengthy, flavorful finish.",
                    price: "$16.99",
                    imageUrl:
                        "https://spoonacular.com/productImages/428475-312x231.jpg",
                    averageRating: 0.9,
                    ratingCount: 4.0,
                    score: 0.823076923076923,
                    link: "https://www.amazon.com/NV-Solera-Cream-Sherry-750/dp/B00HSME8OW?tag=spoonacular-20",
                },
            ],
        },
        instructions:
            "<ol><li>Preheat Oven 350 degrees:</li><li>Combine sliced apples, lemon zest, dash of ground cloves and sugar in a bowl and toss. Place in a deep dish buttered baking dish.</li><li>In a smaller bowl combine the flour, sugar, brown sugar and butter. Mix this together with your fingers until it becomes crumbly. Place this mixture on top of the apples.</li><li>Bake about 40-45 minutes, until the topping gets a little golden color.</li></ol>",
        analyzedInstructions: [
            {
                name: "Preheat Oven 350 degrees",
                steps: [
                    {
                        number: 1,
                        step: "Combine sliced apples, lemon zest, dash of ground cloves and sugar in a bowl and toss.",
                        ingredients: [
                            {
                                id: 2011,
                                name: "ground clove",
                                localizedName: "ground clove",
                                image: "cloves.jpg",
                            },
                            {
                                id: 9156,
                                name: "lemon zest",
                                localizedName: "lemon zest",
                                image: "zest-lemon.jpg",
                            },
                            {
                                id: 9003,
                                name: "apple",
                                localizedName: "apple",
                                image: "apple.jpg",
                            },
                            {
                                id: 19335,
                                name: "sugar",
                                localizedName: "sugar",
                                image: "sugar-in-bowl.png",
                            },
                        ],
                        equipment: [
                            {
                                id: 404783,
                                name: "bowl",
                                localizedName: "bowl",
                                image: "bowl.jpg",
                            },
                        ],
                    },
                    {
                        number: 2,
                        step: "Place in a deep dish buttered baking dish.In a smaller bowl combine the flour, sugar, brown sugar and butter.",
                        ingredients: [
                            {
                                id: 19334,
                                name: "brown sugar",
                                localizedName: "brown sugar",
                                image: "dark-brown-sugar.png",
                            },
                            {
                                id: 1001,
                                name: "butter",
                                localizedName: "butter",
                                image: "butter-sliced.jpg",
                            },
                            {
                                id: 20081,
                                name: "all purpose flour",
                                localizedName: "all purpose flour",
                                image: "flour.png",
                            },
                            {
                                id: 19335,
                                name: "sugar",
                                localizedName: "sugar",
                                image: "sugar-in-bowl.png",
                            },
                        ],
                        equipment: [
                            {
                                id: 404646,
                                name: "baking pan",
                                localizedName: "baking pan",
                                image: "roasting-pan.jpg",
                            },
                            {
                                id: 404783,
                                name: "bowl",
                                localizedName: "bowl",
                                image: "bowl.jpg",
                            },
                        ],
                    },
                    {
                        number: 3,
                        step: "Mix this together with your fingers until it becomes crumbly.",
                        ingredients: [],
                        equipment: [],
                    },
                    {
                        number: 4,
                        step: "Place this mixture on top of the apples.",
                        ingredients: [
                            {
                                id: 9003,
                                name: "apple",
                                localizedName: "apple",
                                image: "apple.jpg",
                            },
                        ],
                        equipment: [],
                    },
                    {
                        number: 5,
                        step: "Bake about 40-45 minutes, until the topping gets a little golden color.",
                        ingredients: [],
                        equipment: [
                            {
                                id: 404784,
                                name: "oven",
                                localizedName: "oven",
                                image: "oven.jpg",
                            },
                        ],
                        length: {
                            number: 45,
                            unit: "minutes",
                        },
                    },
                ],
            },
        ],
        originalId: null,
        spoonacularSourceUrl:
            "https://spoonacular.com/easy-delish-apple-crumble-641803",
    },
];
